import {
  UserProfile,
  Client,
  CaseNote,
  RestrictivePractice,
  Incident,
  Lead,
  Practitioner,
  ABCLog,
  BSPDocument,
  BillingClaim,
  AuditLog,
  CommunicationLog,
  NDISSupportItem
} from '@/types';

export const INITIAL_USERS: UserProfile[] = [
  {
    id: 'usr-1',
    name: 'Dr. Sarah Jenkins',
    email: 'sarah.jenkins@breakthrough.org.au',
    role: 'ADMIN',
    position: 'Clinical Director & Lead Behaviour Practitioner',
    practitionerId: 'prac-1',
    workerScreeningStatus: 'Active',
    workerScreeningExpiry: '2028-11-15',
    policeCheckExpiry: '2027-04-20',
    ndisOrientationDone: true,
    activeCaseload: 8,
  },
  {
    id: 'usr-2',
    name: 'Marcus Vance',
    email: 'marcus.vance@breakthrough.org.au',
    role: 'PRACTITIONER',
    position: 'Senior Behaviour Support Practitioner',
    practitionerId: 'prac-2',
    workerScreeningStatus: 'Active',
    workerScreeningExpiry: '2027-08-30',
    policeCheckExpiry: '2026-12-10',
    ndisOrientationDone: true,
    activeCaseload: 12,
  },
  {
    id: 'usr-3',
    name: 'Elena Rostova',
    email: 'elena.rostova@breakthrough.org.au',
    role: 'VIEWER',
    position: 'NDIS Quality & Compliance Officer',
    workerScreeningStatus: 'Active',
    workerScreeningExpiry: '2028-02-14',
    policeCheckExpiry: '2027-01-18',
    ndisOrientationDone: true,
    activeCaseload: 0,
  },
];

export const INITIAL_CLIENTS: Client[] = [
  {
    id: 'cli-101',
    ndisNumber: '430891204',
    name: 'Jordan Miller',
    dateOfBirth: '2005-04-12',
    status: 'Active',
    primaryDisability: 'Autism Spectrum Disorder (Level 3)',
    secondaryDisabilities: ['Intellectual Disability', 'Sensory Processing Sensitivity'],
    goals: [
      {
        id: 'g-1',
        title: 'Develop emotion regulation strategies during noisy public transitions',
        category: 'Capacity Building',
        targetDate: '2026-12-31',
        progressPercent: 65,
        status: 'In Progress',
        gasScore: 0,
        gasHistory: [
          { date: '2026-03-01', score: -2, note: 'Baseline assessment: Frequent escalation during loud transitions' },
          { date: '2026-05-15', score: -1, note: 'Partial progress: Uses noise-cancelling headphones when prompted' },
          { date: '2026-08-01', score: 0, note: 'Expected outcome reached: Initiates headphone use independently' },
        ],
      },
      {
        id: 'g-2',
        title: 'Increase independent communication using AAC tablet during meal times',
        category: 'Capacity Building',
        targetDate: '2026-10-15',
        progressPercent: 80,
        status: 'In Progress',
        gasScore: 1,
        gasHistory: [
          { date: '2026-04-10', score: -1, note: 'Requires verbal prompts to navigate AAC folder' },
          { date: '2026-07-20', score: 1, note: 'Somewhat higher than expected: Spontaneously creates 3-word requests' },
        ],
      },
    ],
    planStartDate: '2025-07-01',
    planEndDate: '2026-06-30',
    totalBudget: 42500,
    allocatedBudget: 35000,
    spentBudget: 22800,
    primaryPractitionerId: 'prac-2',
    primaryPractitionerName: 'Marcus Vance',
    riskLevel: 'High',
    emergencyContact: {
      name: 'Karen Miller',
      relationship: 'Mother / Primary Carer',
      phone: '0412 889 012',
    },
    restrictivePracticesActive: true,
    createdAt: '2025-07-02T09:00:00Z',
    updatedAt: '2026-08-01T14:20:00Z',
  },
  {
    id: 'cli-102',
    ndisNumber: '431002981',
    name: 'Chloe Zhang',
    dateOfBirth: '1998-09-24',
    status: 'Active',
    primaryDisability: 'Acquired Brain Injury (ABI)',
    secondaryDisabilities: ['Expressive Aphasia'],
    goals: [
      {
        id: 'g-3',
        title: 'Maintain community participation 3 days per week with positive behavior supports',
        category: 'Social & Community',
        targetDate: '2026-11-30',
        progressPercent: 45,
        status: 'In Progress',
      },
    ],
    planStartDate: '2025-09-15',
    planEndDate: '2026-09-14',
    totalBudget: 38000,
    allocatedBudget: 30000,
    spentBudget: 14200,
    primaryPractitionerId: 'prac-1',
    primaryPractitionerName: 'Dr. Sarah Jenkins',
    riskLevel: 'Medium',
    emergencyContact: {
      name: 'David Zhang',
      relationship: 'Brother',
      phone: '0433 112 456',
    },
    restrictivePracticesActive: false,
    createdAt: '2025-09-16T11:30:00Z',
    updatedAt: '2026-08-04T10:15:00Z',
  },
  {
    id: 'cli-103',
    ndisNumber: '438902115',
    name: 'Liam O\'Connor',
    dateOfBirth: '2012-01-30',
    status: 'Onboarding',
    primaryDisability: 'Global Developmental Delay & Challenging Behaviours',
    goals: [],
    planStartDate: '2026-02-01',
    planEndDate: '2027-01-31',
    totalBudget: 28000,
    allocatedBudget: 15000,
    spentBudget: 1200,
    primaryPractitionerId: 'prac-2',
    primaryPractitionerName: 'Marcus Vance',
    riskLevel: 'Critical',
    emergencyContact: {
      name: 'Sean O\'Connor',
      relationship: 'Father',
      phone: '0421 990 882',
    },
    restrictivePracticesActive: true,
    createdAt: '2026-02-05T08:00:00Z',
    updatedAt: '2026-08-08T16:00:00Z',
  },
];

export const INITIAL_CASE_NOTES: CaseNote[] = [
  {
    id: 'cn-1',
    clientId: 'cli-101',
    clientName: 'Jordan Miller',
    practitionerId: 'prac-2',
    practitionerName: 'Marcus Vance',
    date: '2026-08-05',
    sessionDurationMinutes: 90,
    format: 'SIMPL',
    subjective: 'Jordan expressed high arousal prior to transport to day program due to loud construction nearby.',
    objective: 'Practitioner modeled deep breathing and visual schedule token system. Jordan accepted noise-cancelling headphones within 4 minutes.',
    assessment: 'Proactive environmental modification reduced physical agitation from baseline 8/10 to 3/10.',
    plan: 'Continue training support staff on early antecedent cues. Next session on Thursday.',
    linkedGoalIds: ['g-1'],
    status: 'Approved',
    flaggedForReview: false,
    createdAt: '2026-08-05T11:00:00Z',
    updatedAt: '2026-08-05T14:00:00Z',
  },
  {
    id: 'cn-2',
    clientId: 'cli-102',
    clientName: 'Chloe Zhang',
    practitionerId: 'prac-1',
    practitionerName: 'Dr. Sarah Jenkins',
    date: '2026-08-06',
    sessionDurationMinutes: 60,
    format: 'BIRP',
    subjective: 'Chloe reported feeling overwhelmed during community shopping trial.',
    objective: 'Implemented 15-minute quiet break in cafe. Reviewed choice board for emergency exit route.',
    assessment: 'Chloe self-advocated using her AAC device to request a break for the first time.',
    plan: 'Fading practitioner prompts; carer to observe next week.',
    linkedGoalIds: ['g-3'],
    status: 'Approved',
    flaggedForReview: false,
    createdAt: '2026-08-06T15:30:00Z',
    updatedAt: '2026-08-06T16:00:00Z',
  },
];

export const INITIAL_RESTRICTIVE_PRACTICES: RestrictivePractice[] = [
  {
    id: 'rp-1',
    clientId: 'cli-101',
    clientName: 'Jordan Miller',
    practiceType: 'Environmental',
    description: 'Locked kitchen cupboard containing cleaning agents and sharp utensils to prevent severe pica / self-harm during high-arousal episodes.',
    status: 'Authorized',
    authorizationBody: 'VIC Senior Practitioner & NDIS Quality Commission',
    authorizationReference: 'RPR-2025-VIC-88102',
    startDate: '2025-10-01',
    expiryDate: '2026-09-30',
    reductionPlanSummary: 'Gradual introduction of supervised cooking trials with visual safety cues to fade lock requirement by 50% in 6 months.',
    monthlyReportStatus: 'Submitted',
    lastReportedDate: '2026-08-01',
  },
  {
    id: 'rp-2',
    clientId: 'cli-103',
    clientName: 'Liam O\'Connor',
    practiceType: 'Chemical',
    description: 'Low-dose prescribed PRN anti-anxiety medication prior to medical appointments when severe self-injurious behaviour escalates.',
    status: 'Active',
    authorizationBody: 'NDIS Quality & Safeguards Commission Panel',
    authorizationReference: 'RPR-2026-VIC-90211',
    startDate: '2026-03-01',
    expiryDate: '2027-02-28',
    reductionPlanSummary: 'Desensitization protocol in progress with Occupational Therapy.',
    monthlyReportStatus: 'Due',
  },
];

export const INITIAL_INCIDENTS: Incident[] = [
  {
    id: 'inc-101',
    clientId: 'cli-101',
    clientName: 'Jordan Miller',
    practitionerId: 'prac-2',
    practitionerName: 'Marcus Vance',
    incidentDate: '2026-07-28T14:15:00Z',
    severity: 'High',
    status: 'Reported to NDIS Commission',
    isNdisReportable: true,
    ndis24hrNotified: true,
    ndis5daySubmitted: true,
    description: 'Participant engaged in severe head-banging against vehicle window during transport after sudden schedule change.',
    immediateActionTaken: 'Driver safely pulled over. Practitioner applied sensory weighted blanket and verbal calming script.',
    rootCauseAnalysis: 'Unannounced shift in route combined with elevated background noise level.',
    correctiveActions: 'Vehicle now equipped with visual route map; driver briefed to notify 10 mins prior to detours.',
    reportedBy: 'Marcus Vance (Senior BSP)',
    createdAt: '2026-07-28T15:00:00Z',
  },
];

export const INITIAL_LEADS: Lead[] = [
  {
    id: 'lead-1',
    prospectName: 'Ethan Wright',
    ndisNumber: '439901233',
    contactName: 'Amanda Wright',
    contactEmail: 'amanda.wright@example.com',
    contactPhone: '0488 223 901',
    stage: 'Screening & Qualification',
    source: 'Support Coordinator Referral',
    estimatedPlanValue: 24000,
    assignedPractitionerId: 'prac-1',
    assignedPractitionerName: 'Dr. Sarah Jenkins',
    notes: 'Requires urgent Behaviour Support Plan for residential group home placement.',
    createdAt: '2026-08-02T10:00:00Z',
    updatedAt: '2026-08-05T11:20:00Z',
  },
];

export const INITIAL_PRACTITIONERS: Practitioner[] = [
  {
    id: 'prac-1',
    name: 'Dr. Sarah Jenkins',
    email: 'sarah.jenkins@breakthrough.org.au',
    phone: '0411 200 301',
    position: 'Senior Behaviour Support Practitioner',
    qualification: 'Ph.D. Clinical Psychology, BCBA-D',
    ndisRegistrationNumber: 'PR-881902',
    pbsRegistrationLevel: 'Advanced Practitioner',
    specialties: ['High Intensity Behaviours', 'Restrictive Practices', 'Trauma-Informed Care', 'Intellectual Disability'],
    status: 'ACTIVE / APPROVED',
    workerScreeningNumber: 'NWSC-VIC-991201',
    workerScreeningExpiry: '2028-11-15',
    wwccNumber: 'WWCC-9918230-V',
    wwccExpiry: '2028-11-15',
    screeningStatus: 'Valid',
    screeningExpiryDate: '2028-11-15',
    policeCheckExpiryDate: '2027-04-20',
    ndisOrientationCompleted: true,
    cpdHoursThisYear: 32,
    caseloadLimit: 10,
    activeCaseloadCount: 8,
    historicalSuccessRate: 98,
    completedSessionsCount: 420,
    rating: 4.95,
  },
  {
    id: 'prac-2',
    name: 'Marcus Vance',
    email: 'marcus.vance@breakthrough.org.au',
    phone: '0422 300 402',
    position: 'Senior Behaviour Support Practitioner',
    qualification: 'M.Sc. Applied Behaviour Analysis',
    ndisRegistrationNumber: 'PR-441209',
    pbsRegistrationLevel: 'Proficient Practitioner',
    specialties: ['Autism Spectrum Disorder', 'AAC Communication', 'School & Community Transitions', 'Functional Behaviour Assessments'],
    status: 'ACTIVE / APPROVED',
    workerScreeningNumber: 'NWSC-VIC-448102',
    workerScreeningExpiry: '2027-08-30',
    wwccNumber: 'WWCC-4481920-V',
    wwccExpiry: '2027-08-30',
    screeningStatus: 'Valid',
    screeningExpiryDate: '2027-08-30',
    policeCheckExpiryDate: '2026-12-10',
    ndisOrientationCompleted: true,
    cpdHoursThisYear: 28,
    caseloadLimit: 15,
    activeCaseloadCount: 12,
    historicalSuccessRate: 94,
    completedSessionsCount: 310,
    rating: 4.88,
  },
  {
    id: 'prac-3',
    name: 'Liam Davies',
    email: 'liam.davies@breakthrough.org.au',
    phone: '0433 400 503',
    position: 'Occupational Therapist',
    qualification: 'B.App.Sc (Occupational Therapy) - AHPRA Registered',
    ndisRegistrationNumber: 'PR-662104',
    pbsRegistrationLevel: 'Proficient Practitioner',
    specialties: ['Sensory Profiles', 'Environmental Adaptation', 'Assistive Tech Assessments', 'Fine Motor & Regulation'],
    status: 'ACTIVE / APPROVED',
    workerScreeningNumber: 'NWSC-VIC-772199',
    workerScreeningExpiry: '2028-06-12',
    wwccNumber: 'WWCC-7721094-V',
    wwccExpiry: '2028-06-12',
    screeningStatus: 'Valid',
    screeningExpiryDate: '2028-06-12',
    policeCheckExpiryDate: '2027-08-14',
    ndisOrientationCompleted: true,
    cpdHoursThisYear: 30,
    caseloadLimit: 12,
    activeCaseloadCount: 7,
    historicalSuccessRate: 96,
    completedSessionsCount: 260,
    rating: 4.92,
  },
  {
    id: 'prac-4',
    name: 'Chloe Taylor',
    email: 'chloe.taylor@breakthrough.org.au',
    phone: '0444 500 604',
    position: 'Speech Pathologist',
    qualification: 'M.Sp.Path - Certified Practising Speech Pathologist (CPSP)',
    ndisRegistrationNumber: 'PR-551029',
    pbsRegistrationLevel: 'Core Practitioner',
    specialties: ['Augmentative & Alternative Communication (AAC)', 'Receptive Language', 'Social Interaction Skills', 'Mealtime Management'],
    status: 'ACTIVE / APPROVED',
    workerScreeningNumber: 'NWSC-VIC-551829',
    workerScreeningExpiry: '2027-10-22',
    wwccNumber: 'WWCC-5519820-V',
    wwccExpiry: '2027-10-22',
    screeningStatus: 'Valid',
    screeningExpiryDate: '2027-10-22',
    policeCheckExpiryDate: '2027-02-15',
    ndisOrientationCompleted: true,
    cpdHoursThisYear: 26,
    caseloadLimit: 14,
    activeCaseloadCount: 9,
    historicalSuccessRate: 97,
    completedSessionsCount: 195,
    rating: 4.90,
  },
  {
    id: 'prac-5',
    name: 'Zara Patel',
    email: 'zara.patel@breakthrough.org.au',
    phone: '0455 600 705',
    position: 'Core Behaviour Specialist',
    qualification: 'B.Psych (Hons), PBS Core Registered Practitioner',
    ndisRegistrationNumber: 'PR-339102',
    pbsRegistrationLevel: 'Core Practitioner',
    specialties: ['Routine Structuring', 'Skill Acquisition', 'Community Participation', 'Proactive De-escalation'],
    status: 'ACTIVE / APPROVED',
    workerScreeningNumber: 'NWSC-VIC-339102',
    workerScreeningExpiry: '2026-09-15',
    wwccNumber: 'WWCC-3391022-V',
    wwccExpiry: '2026-09-15',
    screeningStatus: 'Expiring Soon',
    screeningExpiryDate: '2026-09-15',
    policeCheckExpiryDate: '2026-08-30',
    ndisOrientationCompleted: true,
    cpdHoursThisYear: 18,
    caseloadLimit: 10,
    activeCaseloadCount: 4,
    historicalSuccessRate: 91,
    completedSessionsCount: 88,
    rating: 4.75,
  },
];

export const INITIAL_ABC_LOGS: ABCLog[] = [
  {
    id: 'abc-1',
    clientId: 'cli-101',
    clientName: 'Jordan Miller',
    timestamp: '2026-08-07T10:30:00Z',
    timeOfDay: '10:30',
    dayOfWeek: 'Friday',
    antecedent: 'Transition from free time to structured group task.',
    behavior: 'Vocal frustration, pushing desk chair backward.',
    consequence: 'Carer offered 2-minute visual timer and break corner.',
    intensity: 3,
    durationMinutes: 6,
    location: 'Day Program Activity Room',
    perceivedFunction: 'Escape/Avoidance',
    recordedBy: 'Support Worker Dave',
  },
];

export const INITIAL_BSP_DOCUMENTS: BSPDocument[] = [
  {
    id: 'bsp-1',
    clientId: 'cli-101',
    clientName: 'Jordan Miller',
    version: 'v2.1',
    status: 'Active',
    summary: 'Comprehensive Positive Behaviour Support Plan focused on sensory self-regulation and environmental predictability.',
    primaryBehaviorsOfConcern: [
      'Physical agitation during unannounced noise spikes',
      'Property disruption during task demand transitions',
    ],
    proactiveStrategies: [
      'Visual schedule board with velcro time markers',
      'Sensory break every 45 minutes',
      'Noise-cancelling headphones kept accessible',
    ],
    reactiveStrategies: [
      'Provide calm low-arousal space',
      'Use 2-word neutral vocal prompts ("Safe space", "Headphones on")',
    ],
    restrictivePractices: INITIAL_RESTRICTIVE_PRACTICES.filter((r) => r.clientId === 'cli-101'),
    reviewDate: '2026-12-01',
    authorName: 'Marcus Vance (Senior BSP)',
    lastUpdated: '2026-08-01',
  },
];

export const INITIAL_BILLING_CLAIMS: BillingClaim[] = [
  {
    id: 'clm-1',
    clientId: 'cli-101',
    clientName: 'Jordan Miller',
    ndisNumber: '430891204',
    serviceDate: '2026-08-05',
    ndisSupportItem: '07_002_0115_8_3 - Specialist Behavioural Intervention Support',
    supportItemCode: '07_002_0115_8_3',
    hours: 1.5,
    unitRate: 214.41,
    totalAmount: 321.62,
    status: 'Approved',
    invoiceNumber: 'INV-2026-0891',
  },
];

export const INITIAL_SUPPORT_ITEMS: NDISSupportItem[] = [
  {
    code: '07_002_0115_8_3',
    name: 'Specialist Behavioural Intervention Support',
    category: 'Capacity Building - Improved Relationships',
    pricePerUnit: 214.41,
    unitOfMeasure: 'Hour',
  },
  {
    code: '07_004_0115_8_3',
    name: 'Individual Behaviour Support Plan Development & Training',
    category: 'Capacity Building - Improved Relationships',
    pricePerUnit: 214.41,
    unitOfMeasure: 'Hour',
  },
  {
    code: '15_056_0128_1_3',
    name: 'Assessment Recommendation Therapy Support - Allied Health',
    category: 'Capacity Building - Improved Daily Living',
    pricePerUnit: 193.99,
    unitOfMeasure: 'Hour',
  },
];

export const INITIAL_AUDIT_LOGS: AuditLog[] = [
  {
    id: 'aud-1',
    timestamp: '2026-08-08T11:20:00Z',
    actorId: 'usr-1',
    actorName: 'Dr. Sarah Jenkins',
    actorRole: 'ADMIN',
    action: 'BSP Plan Approved',
    entity: 'BSPDocument',
    entityId: 'bsp-1',
    details: 'Approved v2.1 Behaviour Support Plan for Jordan Miller after panel review.',
    ipAddress: '10.0.4.12',
  },
];

export const INITIAL_COMMUNICATIONS: CommunicationLog[] = [
  {
    id: 'comm-1',
    entityType: 'Client',
    entityId: 'cli-101',
    entityName: 'Jordan Miller',
    type: 'Phone Call',
    timestamp: '2026-08-04T10:00:00Z',
    authorName: 'Marcus Vance',
    summary: 'Spoke with mother Karen regarding home transport sensory adjustments.',
    followUpRequired: true,
    followUpDate: '2026-08-15',
  },
];
